#! /usr/bin/env node

if( typeof module !== 'undefined' )
{
  let _ = require( '../../Tools.s' );
  _.include( 'wFiles' );
  _.include( 'wProcess' );
}

let _ = wTools;
let shell = _.process.startNjsPassingThrough
({
  execPath : _.path.join( __dirname, 'MainTop.s' ),
  verbosity : 0,
});